(define (make-stream items . eos)
  (if (null? eos)
      (make-stream items #f)
      (list items (car eos))))
(define (peek stream)
  (if (null? (car stream))
      (cadr stream)
      (caar stream)))
(define (peek-2 stream)
  (if (null? (car stream))
      (cadr stream)
      (if (null? (car stream))
          (cadr stream)
          (if (null? (cdar stream))
              (list (caar stream))
              (list (caar stream) (cadar stream))))))
(define (next stream)
  (let ((n (peek stream)))
    (if (not (null? (car stream)))
        (set-car! stream (cdr (car stream))))
    n))
    
                 
